sudo: required
services:
  - docker

before_install:
  - docker build -t euvrisko/docker-app -f Dockerfile.dev .

script:
  - docker run euvrisko/docker-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-app"
  env: "DockerApp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-686143944085"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
